name: fast_expressions
description: Fast Expressions is an expression parser and evaluation library.
version: 0.1.1
homepage: https://github.com/mezoni/fast_expressions
topics:
  - expressions
  - parser
environment:
  sdk: '>=3.0.0 <4.0.0'
dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.4