// This code was generated by the tool, do not modify it manually
// https://pub.dev/packages/peg
import 'dart:convert';
import 'expression_parser.dart';
export 'expression_parser.dart';

/// The [ExpressionConverter] converts data to [Expression] value.
///
/// If event-based parsing is required, then the corresponding parser instance
/// (with event handlers) must be passed as a constructor argument.
class ExpressionConverter with Converter<String, Expression> {
  final ExpressionParser _parser;
  ExpressionConverter({
    ExpressionParser? parser,
  }) : _parser = parser ?? ExpressionParser();
  @override
  Expression convert(String input) {
    final result = parseString(_parser.parseStart, input);
    return result;
  }
}
